[package]
name = "queue_alert_server"
version = "0.1.0"
authors = ["Andy Ealovega <andrew@ealovega.dev>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
web-push = "0.7.2"
actix-web = "3"
base64 = "0.13.0"
dashmap = "4.0.2"
actix-files = "0.5.0"

log = "0.4.14"
simplelog = "0.10.0"